baseurl = "https://kdf.csco.cloud/"
languageCode = "en-us"
title = "KDF"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
        # General information
        author = "SSO Arch Team"
        description = "Kubernetes Development Framework (KDF)"
        copyright = "Released under the Apache-2.0 license"

        # Repository
        provider = "GitHub"
        repo_url = "https://github.com/cisco-sso/kdf"

        version = "0.1.0"
        logo = "images/logo.png"
        favicon = ""

        permalink = "#"

        # Custom assets
        # custom_css = ["https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"]
        # custom_js  = ["https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"]
        custom_css = ["stylesheets/hugo-material-docs_application.css"]

        # Syntax highlighting theme
        highlight_css  = ""

        [params.palette]
        primary = "red"
        accent  = "teal"

        [params.font]
        text = "Ubuntu"
        code = "Ubuntu Mono"

[social]
        github  = "cisco-sso"

[[menu.main]]
        name   = "About"
        url    = "/"
        weight = 10

[[menu.main]]
        name       = "Getting Started"
        url        = "getting-started/"
        weight     = 20
        identifier = "getting-started"

[[menu.main]]
        name       = "Linux"
        url        = "getting-started/linux/"
        parent     = "getting-started"

[[menu.main]]
        name       = "Mac"
        url        = "getting-started/mac/"
        parent     = "getting-started"

[[menu.main]]
        name       = "Windows"
        url        = "getting-started/windows/"
        parent     = "getting-started"

[[menu.main]]
        name   = "Patterns"
        url    = "patterns/"
        weight = 30

[[menu.main]]
        name   = "Tools"
        url    = "tools/"
        weight = 40

[[menu.main]]
        name   = "Deployment Packages"
        url    = "deployment-packages/"
        weight = 50

[[menu.main]]
        name   = "Kubernetes"
        url    = "kubernetes/"
        weight = 60

[[menu.main]]
        name   = "Training"
        url    = "training/"
        weight = 70

[[menu.main]]
        name   = "Backlog"
        url    = "backlog/"
        weight = 80

[[menu.main]]
        name   = "Team"
        url    = "team/"
        weight = 100

[blackfriday]
        smartypants = true
        fractions = true
        smartDashes = true
        plainIDAnchors = true
